import { GoogleGenAI, ThinkingLevel } from "@google/genai";
import { getEnv } from "@/lib/env";
import type { SmileResult } from "@/lib/smile";
import { buildQueryText, buildUserMessage, SYSTEM_PROMPT } from "./prompt";
import { EMBEDDING_DIMENSIONS, EMBEDDING_MODEL, findRelevantTips } from "./retrieval";
import { TIPS } from "./tips";
// Generated by `npm run tips:embed`; bundled with the app so tips are never re-embedded at runtime.
import tipEmbeddings from "./tips-embeddings.json";

export class CoachUnavailableError extends Error {
  constructor() {
    super("GEMINI_API_KEY is not set");
    this.name = "CoachUnavailableError";
  }
}

let client: GoogleGenAI | undefined;

function getClient(): GoogleGenAI {
  const apiKey = getEnv().GEMINI_API_KEY;
  if (!apiKey) throw new CoachUnavailableError();
  client ??= new GoogleGenAI({ apiKey });
  return client;
}

/**
 * Retrieval-augmented generation in three steps:
 * 1. embed a short description of the result,
 * 2. retrieve the 3 closest tips,
 * 3. ask the model for short feedback that uses only those tips.
 */
export async function generateCoachFeedback(result: SmileResult): Promise<string> {
  const ai = getClient();

  // 1. Embed the query. RETRIEVAL_QUERY pairs with the RETRIEVAL_DOCUMENT used for the tips.
  const query = await ai.models.embedContent({
    model: EMBEDDING_MODEL,
    contents: buildQueryText(result),
    config: { taskType: "RETRIEVAL_QUERY", outputDimensionality: EMBEDDING_DIMENSIONS },
  });
  const queryEmbedding = query.embeddings?.[0]?.values;
  if (!queryEmbedding) throw new Error("Embedding response was empty");

  // 2. Retrieve.
  const tipIds = findRelevantTips(queryEmbedding, tipEmbeddings.tips, 3);
  const tips = TIPS.filter((tip) => tipIds.includes(tip.id));

  // 3. Generate. Small output and minimal thinking keep each call cheap and fast.
  const response = await ai.models.generateContent({
    model: getEnv().GEMINI_MODEL,
    contents: buildUserMessage(result, tips),
    config: {
      systemInstruction: SYSTEM_PROMPT,
      maxOutputTokens: 300,
      thinkingConfig: { thinkingLevel: ThinkingLevel.MINIMAL },
    },
  });

  const usage = response.usageMetadata;
  console.info("Coach tokens:", {
    model: getEnv().GEMINI_MODEL,
    tips: tipIds,
    input: usage?.promptTokenCount,
    cached: usage?.cachedContentTokenCount ?? 0,
    output: usage?.candidatesTokenCount,
    thinking: usage?.thoughtsTokenCount ?? 0,
  });

  const text = response.text?.trim();
  if (!text) throw new Error("Coach response was empty");
  return text;
}
